GET http://localhost:8080/api/customers/

###
POST http://localhost:8080/api/customers/create
Content-Type: application/json

{
    "name":"Temp2", 
    "email":"email2@email.com"
}

###
DELETE http://localhost:8080/api/customers/
Content-Type: application/json

{
    "customerId":"cus_MhNgZmxym2qopA"
}

###
GET http://localhost:8080/api/payments/stripe-public-key

###
POST http://localhost:8080/api/customers/create
Content-Type: application/json

{
    "address":"123 main st",
    "name":"temp4", 
    "email":"temp4@email.com"
}