GET http://localhost:8080/api/listing

###

GET http://localhost:8080/api/listing/4

###

POST http://localhost:8080/api/listing
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb2xsZWdlLWNvbW1lcmNlIiwic3ViIjoiSm9obkRvZSIsInVzZXJfaWQiOjEsImF1dGhvcml0aWVzIjoiIiwiZXhwIjoxNjY2ODA4ODgxfQ.NlnXKj9d-PQsyzWO_YUcb5gOh81qrkIV0w_7T7iIeRU

{
    "available":true,
    "userId":4,
    "itemId":2,
    "serviceId":0
}

###

DELETE http://localhost:8080/api/listing/2

###
PUT http://localhost:8080/api/listing/4
Content-Type: application/json

{
    "listingId": 4,
    "available":true,
    "userId":3,
    "itemId":1,
    "serviceId":0
}
