GET http://localhost:8080/api/service

###


###

POST http://localhost:8080/api/service
Content-Type: application/json

{
    "name":"mail delivery",
    "description":"mail",
    "pricePerHour":5.99,
    "category":"OTHER",
    "userId":2,
    "available":false
}

###

DELETE http://localhost:8080/api/service/1

###
PUT http://localhost:8080/api/service/4
Content-Type: application/json

{
    "serviceId":4,
    "name":"mail delivery2",
    "description":"mail2",
    "pricePerHour":5.99,
    "category":"DELIVERY"
}

###

POST http://localhost:8080/api/service
Content-Type: application/json

{
    "name":"mail delivery",
    "description":"mail",
    "pricePerHour":5.99,
    "category":"OTHER",
    "userId":2,
    "available":false
    
}

###
PUT http://localhost:8080/api/service/5
Content-Type: application/json

{
    "serviceId":5,
    "name":"mail 8",
    "description":"mail2",
    "pricePerHour":7.00,
    "category":"mail"
}

###

DELETE http://localhost:8080/api/service/4

###
PUT http://localhost:8080/api/service/4
Content-Type: application/json

{
    "serviceId": 4,
    "name": "jhjkhjkhkj",
    "description": "khjkhjkhjkh",
    "pricePerHour": 99.0,
    "category": "OTHER",
    "userId": 3,
    "location": "North Dakota State University",
    "available": true
  }